apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    version: dev
    product: ContainersEverywhere
spec:
  selector:
    app: website
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-website
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: containerseverywhere.azurecr.io/web:__Build.BuildId__        
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey
      nodeSelector:
          beta.kubernetes.io/os: linux
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dep-db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: microsoft/mssql-server-linux:latest    
        ports:
        - containerPort: 1433      
      nodeSelector:
          beta.kubernetes.io/os: linux